#!/bin/bash

# Este script borra todas las aplicaciones de google de un dispositivo android
# utilizando la herramienta Android Debug Bridge.

function borrarApp(){
    adb shell pm uninstall --user 0 $1
}

if [ "$(adb)" ]
then
    echo "$(tput setaf 2)"ADB está instalado"$(tput sgr0)"
else
    echo "$(tput setaf 1)"ADB no está instalado, instálalo y ejecute el script"$(tput sgr0)"
    exit
fi

while IFS= read -r line
do
    borrarApp $line
done < aplicaciones-borrar.txt