#!/bin/bash

# Este script se utiliza para de-Googelear un telefono android, en caso de
# no tener instalado adb, se le instalará automáticamente

function borrarApp(){
    adb shell pm uninstall --user 0 $1
}

if [ "$(adb)" ]
then
    echo "ADB está instalado"
else
    echo "ADB no está instalado, instálalo y ejecute el script"
    exit
fi

while IFS= read -r line
do
    borrarApp $line
done < aplicaciones-borrar.txt